// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQc8fiQNLZlPcS8XZx07bQaPM7Q64bzoA',
    appId: '1:1037504246378:web:45ca55ceb3c2da93509013',
    messagingSenderId: '1037504246378',
    projectId: 'datesonthego-7edc6',
    authDomain: 'datesonthego-7edc6.firebaseapp.com',
    storageBucket: 'datesonthego-7edc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnLdJQpU-a-TAGV2pi7tkJ5Boo7e6Fkmg',
    appId: '1:1037504246378:android:c3a3057326c714a1509013',
    messagingSenderId: '1037504246378',
    projectId: 'datesonthego-7edc6',
    storageBucket: 'datesonthego-7edc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgOwh1Dxhxal1LeI0Vth7iK_lr2pI2ypQ',
    appId: '1:1037504246378:ios:d1f40f2fe9ef5bd3509013',
    messagingSenderId: '1037504246378',
    projectId: 'datesonthego-7edc6',
    storageBucket: 'datesonthego-7edc6.appspot.com',
    androidClientId: '1037504246378-fdq1fls610oob7fpp2uk2quu2l1kb9v8.apps.googleusercontent.com',
    iosClientId: '1037504246378-dnu8g6iq9n0gregs0t437v1l4drp9osu.apps.googleusercontent.com',
    iosBundleId: 'com.datesonthego.app',
  );
}
